### ISSUE TITLE
Add a rule to detect broken internal links

### ISSUE THREAD

**Issue by cirosantilli** [wooorm/mdast-lint#17]
By internal links I mean:

- `[see this file](another/file.md)`
- `[see this header](#some-header)`

I often avoid writing those because I know they will break sooner or later, but I would really like to use internal links.

If only I had a tool that notified me when either of those broke, that would be awesome ... :-)

Header links are a bit harder since they require you to specify the ID generation rule which is not standardized... but we could just start by copying GitHub's which works well for common headers of most implementations. See: https://github.com/cirosantilli/test/blob/master/md.md#012-uppercase-underline_hyphen-spaces--othersend

On markdownlint: https://github.com/mivok/markdownlint/issues/95

**Comment by wooorm** [comment]
Awesome, it's something I also think a rule could help with this. I'm on holiday right now, will work on this later!

**Comment by wooorm** [comment]
Some first thoughts:

*   **anchor links:** How would this work for something like `#readme`, which directs to the start of the document on GitHub? Would this rule warn?
*   **anchor and relative links:** How about different algorithms? There’s a difference between npm and GitHub...
*    Currently, **mdast-toc** adds `attributes.id` to every heading node, which **mdast-html** compiles to HTML IDs. It has presets for both npm and GitHub. I’d like to externalise that, and probably let **mdast-lint** check that (before defaulting to GitHub style branch/heading links).
*   As noted on the [README](https://github.com/wooorm/mdast-lint#using-mdast-to-fix-your-markdown), I’m in favour of letting tools generate IDs and hard links for you (just like how **mdast-github** expand `@wooorm` to `https://github.com/wooorm`).

@cirosantilli, what do you think?

**Comment by cirosantilli** [comment]
- `#readme`: hard choice. I think it should warn as it is too GH specific, and people should use a top level header and link to it anyway, which works for all markdown files, not just readmes
- different algorithms: yup, that is a pain point. The only real solution is to encode them all, and chose on the config file which one you want to enforce :-(
- externalizing: sounds like a good solution
- I don't understand how that relates to this feature, maybe because I don't fully understand `mdast-github`. Do you mean a tool that you add special markup like [](link_to "My header")`, and it then parses that into `#my-header` for github or any other style you choose? While it is the only solution for portability before standardization, pre processing is really painful :-(

**Comment by wooorm** [comment]
Re the latest point: mdast-github basically expands things like `#12` to `https://github.com/wooorm/mdast/issues/12`. Because that feature only works in commnts/posts on GitHub, not in source code itself.

**mdast-github** could also expand links to files, to links to GitHub, thus `[foo](docs/bar.md#baz)` to `[foo](https://github.com/wooorm/mdast/blob/master/docs/bar.md#baz)`. From a README, linking to `docs/bar.md` is easy but from two nested directories things are getting problematic when you move some files around. Making links absolute fixes that problem. I didn't mean the solution you referenced (although it might indeed be the only solution 😉).

Seems like I have a solid plan on how ti fix this, you’ll hear from me soon! Thanks!

**Comment by wooorm** [comment]
Been a while, but I’ve created a new tool to check a project for dead-links: [**mdast-visit-links**](https://github.com/wooorm/mdast-validate-links). It’s not in mdast-lint because it does some advanced things, like reading all files, adding new files, which are not available in mdast-lint.

It supports any slug mechanism you want (through [**mdast-slug**](https://github.com/wooorm/mdast-slug)), with presets for GitHub and npm. Additionally, it supports links like `https://github.com/wooorm/mdast/blob/master/docs/bar.md#baz` by normalising them based on a given [repository URL](https://github.com/wooorm/mdast-validate-links#configuration).

**Comment by cirosantilli** [comment]
@wooorm thanks! I'll have a look.
